package edu.pjwstk.mas_project_vovkotrub_yaroslav_s18461.gui.view;

import lombok.Data;
import org.springframework.stereotype.Component;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

/**
 * Class representing configuration for the extended vehicle information
 */
@Data
@Component
public class ExtendedVehicleInfo {
    private JButton mainMenuButton;
    private JPanel panel;
    private JTextPane vehicleInfoPane;
    private JTextPane vehicleNamePane;
    private JTextPane vehicleInfoPane2;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel.setBackground(new Color(-3748915));
        panel.setMaximumSize(new Dimension(700, 520));
        panel.setMinimumSize(new Dimension(700, 520));
        panel.setPreferredSize(new Dimension(700, 520));
        vehicleNamePane = new JTextPane();
        vehicleNamePane.setBackground(new Color(-6314842));
        Font vehicleNamePaneFont = this.$$$getFont$$$("Century Gothic", Font.BOLD, 36, vehicleNamePane.getFont());
        if (vehicleNamePaneFont != null) vehicleNamePane.setFont(vehicleNamePaneFont);
        vehicleNamePane.setMaximumSize(new Dimension(700, 50));
        vehicleNamePane.setMinimumSize(new Dimension(700, 50));
        vehicleNamePane.setPreferredSize(new Dimension(700, 50));
        vehicleNamePane.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 0, 0, 0);
        panel.add(vehicleNamePane, gbc);
        mainMenuButton = new JButton();
        mainMenuButton.setBackground(new Color(-16728833));
        Font mainMenuButtonFont = this.$$$getFont$$$("Century Gothic", Font.BOLD, 20, mainMenuButton.getFont());
        if (mainMenuButtonFont != null) mainMenuButton.setFont(mainMenuButtonFont);
        mainMenuButton.setForeground(new Color(-1));
        mainMenuButton.setMaximumSize(new Dimension(196, 60));
        mainMenuButton.setMinimumSize(new Dimension(196, 60));
        mainMenuButton.setPreferredSize(new Dimension(196, 60));
        mainMenuButton.setText("Main menu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(15, 0, 0, 0);
        panel.add(mainMenuButton, gbc);
        vehicleInfoPane2 = new JTextPane();
        vehicleInfoPane2.setBackground(new Color(-6314842));
        Font vehicleInfoPane2Font = this.$$$getFont$$$("Century Gothic", Font.BOLD, 20, vehicleInfoPane2.getFont());
        if (vehicleInfoPane2Font != null) vehicleInfoPane2.setFont(vehicleInfoPane2Font);
        vehicleInfoPane2.setMaximumSize(new Dimension(350, 200));
        vehicleInfoPane2.setMinimumSize(new Dimension(350, 200));
        vehicleInfoPane2.setPreferredSize(new Dimension(350, 200));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.insets = new Insets(15, 15, 0, 15);
        panel.add(vehicleInfoPane2, gbc);
        vehicleInfoPane = new JTextPane();
        vehicleInfoPane.setBackground(new Color(-6314842));
        Font vehicleInfoPaneFont = this.$$$getFont$$$("Century Gothic", Font.BOLD, 20, vehicleInfoPane.getFont());
        if (vehicleInfoPaneFont != null) vehicleInfoPane.setFont(vehicleInfoPaneFont);
        vehicleInfoPane.setMaximumSize(new Dimension(350, 200));
        vehicleInfoPane.setMinimumSize(new Dimension(350, 200));
        vehicleInfoPane.setPreferredSize(new Dimension(350, 200));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.insets = new Insets(15, 15, 0, 15);
        panel.add(vehicleInfoPane, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
