package edu.pjwstk.mas_project_vovkotrub_yaroslav_s18461.gui.view;

import edu.pjwstk.mas_project_vovkotrub_yaroslav_s18461.model.Salon;
import lombok.Data;
import org.springframework.stereotype.Controller;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

@Controller
@Data
public class ListSalons {
    private JPanel salonPanel;
    private JButton mainMenuButton;
    private JList<Salon> salonList;
    private DefaultListModel<Salon> salonListModel;

    private void createUIComponents() {
        salonListModel = new DefaultListModel<>();
        salonList = new JList<>(salonListModel);
        salonList.setCellRenderer(new SalonListCellRender());
    }

    private class SalonListCellRender extends JLabel implements ListCellRenderer<Salon> {

        public SalonListCellRender() {
            setOpaque(true);
        }

        @Override
        public Component getListCellRendererComponent(JList<? extends Salon> jList, Salon salon, int i, boolean b, boolean b1) {
            setText(salon.getName());
            setFont(new Font("Century Gothic", Font.BOLD, 18));
            if (b) {
                setBackground(jList.getSelectionBackground());
                setForeground(jList.getSelectionForeground());
            } else {
                setBackground(jList.getBackground());
                setForeground(jList.getForeground());
            }
            return this;
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        salonPanel = new JPanel();
        salonPanel.setLayout(new GridBagLayout());
        salonPanel.setMaximumSize(new Dimension(700, 520));
        salonPanel.setMinimumSize(new Dimension(700, 520));
        salonPanel.setPreferredSize(new Dimension(700, 520));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setMaximumSize(new Dimension(300, 600));
        scrollPane1.setMinimumSize(new Dimension(300, 600));
        scrollPane1.setPreferredSize(new Dimension(300, 600));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(15, 0, 0, 0);
        salonPanel.add(scrollPane1, gbc);
        Font salonListFont = this.$$$getFont$$$("Century Gothic", Font.BOLD, 18, salonList.getFont());
        if (salonListFont != null) salonList.setFont(salonListFont);
        salonList.setLayoutOrientation(0);
        salonList.setMaximumSize(new Dimension(300, 600));
        salonList.setMinimumSize(new Dimension(300, 600));
        salonList.setPreferredSize(new Dimension(300, 600));
        scrollPane1.setViewportView(salonList);
        mainMenuButton = new JButton();
        mainMenuButton.setBackground(new Color(-16728833));
        Font mainMenuButtonFont = this.$$$getFont$$$("Century Gothic", Font.BOLD, 20, mainMenuButton.getFont());
        if (mainMenuButtonFont != null) mainMenuButton.setFont(mainMenuButtonFont);
        mainMenuButton.setForeground(new Color(-1));
        mainMenuButton.setMaximumSize(new Dimension(196, 60));
        mainMenuButton.setMinimumSize(new Dimension(196, 60));
        mainMenuButton.setOpaque(true);
        mainMenuButton.setPreferredSize(new Dimension(196, 60));
        mainMenuButton.setText("Main menu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(15, 0, 15, 0);
        salonPanel.add(mainMenuButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return salonPanel;
    }

}
